services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - db-data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    env_file:
      - .env
    environment:
      - MONGO_DB=${MONGO_DB}
      - MONGO_URL=${MONGO_URL}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: mongod --config /etc/mongod.conf

  app:
    restart: always
    networks:
      - default
    env_file:
      - .env
    environment:
      - MONGO_DB=${MONGO_DB}
      - MONGO_URL=${MONGO_URL}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

      - TON_CONNECT_SECRET=${TON_CONNECT_SECRET}
      - PAYLOAD_TTL=${PAYLOAD_TTL}
      - PROOF_TTL=${PROOF_TTL}
      - OUR_WALLET=${OUR_WALLET}
      - OUR_WALLET_MNEMONICS=${OUR_WALLET_MNEMONICS}
      - JETTON_MASTER_ADDRESS=${JETTON_MASTER_ADDRESS}
      - TOKEN_SYMBOL=${TOKEN_SYMBOL}

      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=${JWT_REFRESH_TOKEN_EXPIRE_MINUTES}

      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}

      - FRONTEND_URI=${FRONTEND_URI}

      - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    ports:
      - 5000:5000

    depends_on:
      mongodb:
        condition: service_healthy

    build:
      context: "."

  nginx:
      image: nginx:latest
      restart: always
      depends_on:
      - app
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      networks:
        - default

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis_data:/data/redis
    env_file:
      - .env
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} --maxmemory ${REDIS_MAXMEMORY} --maxmemory-policy ${REDIS_MAXMEMORY_POLICY}

volumes:
  db-data:
  mongod.conf:
  redis_data: