services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - db-data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_DB=${MONGO_DB}
      - MONGO_URL=${MONGO_URL}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

  app:
    restart: always
    networks:
      - default
    env_file:
      - .env
    environment:
      - MONGO_DB=${MONGO_DB}
      - MONGO_URL=${MONGO_URL}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

      - TON_CONNECT_SECRET=${TON_CONNECT_SECRET}
      - PAYLOAD_TTL=${PAYLOAD_TTL}
      - PROOF_TTL=${PROOF_TTL}

      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=${JWT_REFRESH_TOKEN_EXPIRE_MINUTES}

    ports:
      - 5000:5000

    depends_on:
      db:
        condition: service_healthy

    build:
      context: "."

volumes:
  db-data: