services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - db-data:/data/db
      - mongod.conf:/etc/mongo/mongod.conf
    env_file:
      - .env
    environment:
      - MONGO_DB=${MONGO_DB}
      - MONGO_URL=${MONGO_URL}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: mongod --config /etc/mongo/mongod.conf

  app:
    restart: always
    networks:
      - default
    env_file:
      - .env
    environment:
      - MONGO_DB=${MONGO_DB}
      - MONGO_URL=${MONGO_URL}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

      - TON_CONNECT_SECRET=${TON_CONNECT_SECRET}
      - PAYLOAD_TTL=${PAYLOAD_TTL}
      - PROOF_TTL=${PROOF_TTL}

      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=${JWT_REFRESH_TOKEN_EXPIRE_MINUTES}

      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}

      - FRONTEND_URI=${FRONTEND_URI}
      - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}

    ports:
      - 5000:5000

    depends_on:
      db:
        condition: service_healthy

    build:
      context: "."

volumes:
  db-data:
  mongod.conf: